### ISSUE TITLE
Add support for using `bdist_nuitka` without setup.py, i.e. pure pyproject setup

### ISSUE THREAD

**Issue by nschloe** [Nuitka/Nuitka#1285]
One can build Nuitka'd wheels via
```
python3 setup.py bdist_nuitka
```
Is it possible to do the same in a [PEP 517](https://www.python.org/dev/peps/pep-0517/)/[518 setting](https://www.python.org/dev/peps/pep-0518/), i.e., without a `setup.py`, but with a `setup.cfg` and a `pyproject.toml`,
```toml
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
```
?
