### ISSUE TITLE
[Question] build nuitka with pyproject.toml, how to include-data-dir?

### ISSUE THREAD

**Issue by Jackiexiao** [Nuitka/Nuitka#1756]
I try to include package data when building a wheel using nuitka, but error occurs and no data is included in .whl

* error
```
FATAL: Error, must specify existing source data directory, not 'frontend/asset' as in 'frontend/asset=frontend/asset'.
```
but frontend/asset/ directory is existed

* help doc: `python -m nuitka -h`
I read the doc, but I don't understand  `/path/some_dir=data/some_dir` means....
```
    --include-data-dir=DIRECTORY
                        Include data files from complete directory in the
                        distribution. This is recursive. Check '--include-
                        data-files' with patterns if you want non-recursive
                        inclusion. An example would be '--include-data-
                        dir=/path/some_dir=data/some_dir' for plain copy, of
                        the whole directory. All files are copied, if you want
                        to exclude files you need to remove them beforehand,
                        or use '--noinclude-data-files' option to remove them.
                        Default empty.
```

* my pyproject.toml
```toml
[build-system]
requires = ["setuptools>=61.0", "wheel", "nuitka", "toml", "orderedset"]
build-backend = "nuitka.distutils.Build"

[nuitka]
nofollow-import-to = ["*.tests", "*.distutils"]
include-data-dir = ["frontend/asset=frontend/asset"]
include-package-data = ["frontend"]
```
* build command
```
python -m build --wheel
```

* Nuitka version

```
(frontend) ➜  pyfrontend git:(v2.0) ✗ python -m nuitka --version
1.0.5
Commercial: None
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) 
Flavor: Anaconda Python
Executable: /home/jackie/anaconda3/envs/frontend/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04
```
thx for your time!!
