### ISSUE TITLE
Code using postponed evaluation of annotations (PEP 563) is rejected with a SyntaxError

### ISSUE THREAD

**Issue by aw1621107** [Nuitka/Nuitka#188]
Nuitka chokes on files that make use of annotations that are only valid with [PEP 563](https://www.python.org/dev/peps/pep-0563/), which was added in Python 3.7. Among other changes, it allows type annotations for methods in a class to use the name of the class in which they were defined. For example, the following is not valid without PEP 563 due to `Foo` not being defined at the point it is used in the type definition:

```python3
class Foo:
    def make_foo() -> Foo:
        return Foo()
```

This is valid in Python 3.7+ when `from __future__ import annotations` is used, and will become the default in Python 4.

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
(ins)awang@sid:/tmp/nuitka$ apt show python3.7
Package: python3.7
Version: 3.7.1-1
<snip>
```
```
(ins)awang@sid:/tmp/nuitka$ python3.7 -m nuitka --version
0.6.1rc7
Python: 3.7.0+ (default, Aug 31 2018, 23:21:37) 
Executable: /home/awang/.cache/pypoetry/virtualenvs/test-py3.7/bin/python3.7
OS: Linux
Arch: x86_64
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

Python was installed using `apt` and Nuitka was installed through `poetry` with the following `pyproject.toml`:

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
nuitka = {git = "https://github.com/Nuitka/Nuitka", branch = "develop"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.

The following file demonstrates the issue:

```python3
from __future__ import annotations

class Foo:
    def make_foo() -> Foo:
        return Foo()
```
```
(ins)awang@sid:/tmp/nuitka$ python3.7 test.py
(ins)awang@sid:/tmp/nuitka$ echo $?
0
(ins)awang@sid:/tmp/nuitka$ python3.7 -m nuitka test.py
  File "test.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

Nuitka is very syntax compatible with standard Python. It is currently running
with Python version '3.7', you might want to specify more clearly with the use
of the precise Python interpreter binary and '-m nuitka', e.g. use this
'python2.7 -m nuitka' option, if that's not the one the program expects.
```
