### ISSUE TITLE
AntiBloat patch when no_docstring

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#2006]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version
```
1.3.6
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe (cl 14.2).
```

* How did you install Nuitka and Python

Installed using pip

### Explanation

Hi, 
i have a similar problem as #1855 for the xgboost package.
So i was trying to follow @kayhayen advice by patching the code with the anti-bloat plugin.
I have write this in the yaml config:
```yaml
- module-name: 'xgboost.sklearn'
  anti-bloat:
    - description: 'remove docstring dependency' 
      replacements-plain:
        'assert XGBModel.fit.__doc__ is not None' : 'XGBModel.fit.__doc__ = "Fit gradient boosting model"'
      when: 'no_docstrings and no_asserts'
```
But when i try to compile i obtain the following error:
```
FATAL: anti-bloat: Identifier 'no_docstrings' in 'when' configuration of module 'xgboost.sklearn' is unknown
```
Am i missing something?
