### ISSUE TITLE
DLL missing for sounddevice

### ISSUE THREAD

**Issue by rweiss123** [Nuitka/Nuitka#2009]
Hi,

when I compile with:
`python -m nuitka --standalone --enable-console  main.py`
with this program:
```
import sounddevice

if __name__ == '__main__':
    print("Hello World")
```

I get this error:
```
Traceback (most recent call last):
  File "C:\work\app\SOUNDD~1\MAIN~1.DIS\sounddevice.py", line 71, in <module sounddevice>
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\work\app\SOUNDD~1\MAIN~1.DIS\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\work\app\SOUNDD~1\MAIN~1.DIS\sounddevice.py", line 83, in <module sounddevice>
OSError: cannot load library 'C:\work\app\SOUNDD~1\MAIN~1.DIS\_sounddevice_data\portaudio-binaries\libportaudio64bit.dll': error 0x7e
```

Nuitka version:
```
python -m nuitka --version
1.3.8
Commercial: None
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe (cl 14.3).
```

pip freeze
```
pip freeze
altgraph==0.17.3
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
contourpy==1.0.6
cycler==0.11.0
docutils==0.19
fonttools==4.38.0
future==0.18.2
idna==3.4
Kivy==2.1.0
kivy-deps.angle==0.3.3
kivy-deps.glew==0.3.1
kivy-deps.sdl2==0.4.5
Kivy-Garden==0.1.5
kiwisolver==1.4.4
matplotlib==3.6.2
Nuitka==1.3.8
numpy==1.23.4
ordered-set==4.1.0
packaging==21.3
pefile==2022.5.30
Pillow==9.2.0
psutil==5.9.4
pycparser==2.21
Pygments==2.13.0
pyinstaller==5.6.1
pyinstaller-hooks-contrib==2022.11
pyparsing==3.0.9
pypiwin32==223
pypref==3.3.0
pyserial==3.5
python-dateutil==2.8.2
pywin32==304
pywin32-ctypes==0.2.0
requests==2.28.1
scipy==1.9.3
six==1.16.0
sounddevice==0.4.5
SoundFile==0.10.3.post1
urllib3==1.26.12
wxPython==4.2.0
zstandard==0.19.0
```

Not using virtualenv. Packages installed using PyCharm.

Best regards,
Reinhard

**Comment by kayhayen** [comment]
Using the information here, would you be able to provide this yourself, Reinhard? 

https://nuitka.net/posts/nuitka-package-config-kickoff.html

Note that you have to use the develop version for the tools to be available.

**Comment by rweiss123** [comment]
Hello Kay,

got it, here the settings for module sounddevice (I only tested arch_amd64):
```
- module-name: 'sounddevice'
  dlls:
    - from_filenames:
        relative_path: '_sounddevice_data/portaudio-binaries'
        prefixes:
          - 'libportaudio64bit'
      when: 'win32 and arch_amd64'
    - from_filenames:
        relative_path: '_sounddevice_data/portaudio-binaries'
        prefixes:
          - 'libportaudio32bit'
      when: 'win32 and arch_x86'
    - from_filenames:
        relative_path: '_sounddevice_data/portaudio-binaries'
        prefixes:
          - 'libportaudio'
      when: 'macos'
```

Some feedback on the kickoff page:
- I think it would have helped me if the page mentioned the name of the Yaml file for the given example.
- nuitka --list-package-data and --list-package-dlls didn't work for me, I got:
```
"c:\Program Files\Python310\python.exe" bin\nuitka --list-package-data=sounddevice
FATAL: Error, doesn't seem that 'sounddevice' is a package on disk.
```
But it was easy enough to locate the files myself.

Best regards,
Reinhard

**Comment by kayhayen** [comment]
I am including your change in 1.4.1 hotfix which is going to come today.

**Comment by kayhayen** [comment]
The thing about this, is that it doesn't install itself as a package, which is pretty unusual. I will take note of that, and improve it, probably we can kind of fallback to distribution name, and go from there to maybe find the paths it installs to for these things.

**Comment by rweiss123** [comment]
Thank you.
Actually I found one more package with a similar behavior:

```
- module-name: 'soundfile'
  dlls:
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile64bit'
      when: 'win32 and arch_amd64'
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile32bit.dll'
      when: 'win32 and arch_x86'
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile'
      when: 'macos'
```

Best regards,
Reinhard
