### ISSUE TITLE
plugin not working for main script

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#2382]
### plug.yml
```yaml
- module-name: '__main__'
  anti-bloat:
    - description: 'textwrap no needed'
      no-auto-follow:
        'textwrap': 'script can alive without it'
```
### Command
```shell
nuitka --standalone --user-package-configuration-file=plug.yml --mingw64 --report=nuitka.xml helloworld.py
```

Here `textwrap` is just for test and I expected to not be included in compilation. But it did include.
