### ISSUE TITLE
Error finding soundfile path on arm64

### ISSUE THREAD

**Issue by BKLronin** [Nuitka/Nuitka#2577]
Hi! 

trying to compile librosa on arm64 (mac 14.1) With python 3.10. and the following packages (shortended):

```
audioread==3.0.1
lameenc==1.6.3
librosa==0.10.1
Nuitka==1.9.1
numba==0.58.1
numpy==1.26.2
PyAudio==0.2.14
pydub==0.25.1
PySide6-Essentials==6.6.0
scikit-learn==1.3.2
scipy==1.11.4
shiboken6==6.6.0
soundfile==0.12.1
```
Version:

```
1.9.1
Commercial: None
Python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/bklronin/Development/venv_11/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).
```
Settings:
```
# nuitka-project: --plugin-enable=pyside6
# nuitka-project: --plugin-enable=numpy
# nuitka-project: --include-package=mido
# nuitka-project: --include-package=librosa
# nuitka-project: --follow-imports
# nuitka-project: --noinclude-numba-mode=nofollow
# nuitka-project: --standalone
# nuitka-project: --macos-create-app-bundle
# nuitka-project: --include-data-files=devices.yaml=devices.yaml
# nuitka-project: --include-data-files=config.yaml=config.yaml
# nuitka-project: --include-data-files=sampler_presets.yaml=sampler_presets.yaml

```

Commandline:

` python -m nuitka --standalone --macos-create-app-bundle app.py ` in env

Error: Appears with all python versions from 3.9 to 3.11
```

Nuitka-Inclusion:INFO: Not including forbidden DLL '/Users/bklronin/Development/venv_11/lib/python3.10/site-packages/PySide6/Qt/plugins/imageformats/libqpdf.dylib'.
FATAL: Error, failed to find path @rpath/libsndfile.1.dylib (resolved DLL to /Users/bklronin/Development/venv_11/lib/python3.10/site-packages/_soundfile_data/libsndfile.1.dylib) for /Users/bklronin/Development/venv_11/lib/python3.10/site-packages/_soundfile_data/libsndfile_arm64.dylib from 'soundfile', please report the bug.
```

**Comment by kayhayen** [comment]
I don't see a minimal reproducer.

**Comment by BKLronin** [comment]
Here you go :
```
# nuitka-project: --plugin-enable=numpy
# nuitka-project: --include-package=librosa
# nuitka-project: --follow-imports
# nuitka-project: --noinclude-numba-mode=error
# nuitka-project: --standalone
# nuitka-project: --macos-create-app-bundle

import librosa
import numpy as np

# Generate a random audio array
sr = 22050  # Sample rate
duration = 3.0  # Duration in seconds
t = np.arange(0, duration, 1.0 / sr)
audio_signal = np.random.randn(len(t))

# Compute MFCC features
mfccs = librosa.feature.mfcc(y=audio_signal, sr=sr, n_mfcc=13)
```
[librosa_minimal.py.zip](https://github.com/Nuitka/Nuitka/files/13466644/librosa_minimal.py.zip)

**Comment by kayhayen** [comment]
The include package is not going to do you much good, it ought to not be necessary or else should be fixed separately.

**Comment by BKLronin** [comment]
Yeah thats a artifact from wildly experimenting.

**Comment by BKLronin** [comment]
I removed all of the NUmba decorators and ended up at the same place as when using 
`# nuitka-project: --noinclude-numba-mode=nofollow`
Then the original error from the post shows up. 
`FATAL: Error, failed to find path @rpath/libsndfile.1.dylib (resolved DLL to /Users/bklronin/Development/venv_11/lib/python3.10/site-packages/_soundfile_data/libsndfile.1.dylib) for /Users/bklronin/Development/venv_11/lib/python3.10/site-packages/_soundfile_data/libsndfile_arm64.dylib from 'soundfile', please report the bug.`

The soundfile `libsndfile_arm64.dylib` is in place and working. Maybe really just a path formatting error etc

**Comment by BKLronin** [comment]
Yep, when I copy and rename the `libsndfile_arm64.dylib` to the requested name it compiles.

So probably the name generation in here for the arrches? `standard.nuitka-package.config yaml`

```
- module-name: 'soundfile'
  dlls:
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile*64bit'
      when: 'win32 and arch_amd64'
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile*32bit'
      when: 'win32 and arch_x86'
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile'
      when: 'macos'
```

**Comment by BKLronin** [comment]
After that I end up at:

Now caused by pyaudio:

`FATAL:     Error, problem with dependency scan of '/Users/bklronin/Development/venv_11/lib/python3.10/site-packages/pyaudio/_portaudio.cpython-310-darwin.so' with '/opt/homebrew/opt/portaudio/lib/libportaudio.2.dylib' please report the bug.`

Seems similar to the existing issue.

When not using the minimal_librosa test.

**Comment by BKLronin** [comment]
File is in place but symlinked to /opt/homebrew/Cellar/portaudio/19.7.0/lib from
/opt/homebrew/opt/portaudio/lib/libportaudio.2.dylib

End of latein

**Comment by kayhayen** [comment]
Homebrew is not the best supported, I only ever try much with CPython, but it could be generally wrong with the DLL name indeed, although I believe it worked. I will try and cover it with something in Nuitka-Watch I guess. It may also be that `librosa` is still an unresolved issue generally. I do recall using it occasionally with success, but maybe not on all platforms yet, the numba issue is heavy. I do however think that there was something that meant that librosa doesn't automatically use numba at all. I will look into it, once the 1.9 release woes are over.

**Comment by BKLronin** [comment]
That would be great. I look into nuitka on every realease cycle as it would fix quite a few problems and enable some planned features. 

I havent found anythin to disable numba except removing all the decorators by "hand" and that seemed to work. At least I could still use certain elements like hpss, mfcc, utils etc.

The `PyAudio` (-> portaudio) issue seems seperate as it is now a requirement of `librosa` but used for IO like `sounddevice`. This is kinda strange as I think it compiled Pyaudio as it should the last time when the code was simpler. 

Should have made a new issue for that probably?

Thank you very much.

**Comment by kayhayen** [comment]
You know, I never fix things by hand, if necessary, I do it with anti-bloat changes, but so far I believe this kind of JIT was at some point generally disabled, but re-enabled later, but in principle works in many programs. I think I regularly compile with librosa, but I am not sure of the versions. If there is anything with pyaudio or whatever package, yes, make a separate issue out of it.

**Comment by kayhayen** [comment]
If you want to help, it would be better to spend you time maybe in this way:

If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

The idea being that you can yourself add missing DLLs, etc. and maybe even fight the need for the JIT there. However, I feel like there is an environment variable to disable it or something like it, one that Nuitka enforced in the past, but that was going too far, since it actually is supposed to be usable for some things.

**Comment by BKLronin** [comment]
Thanks, I tried it with the kickoff method specifically for the `soundfile` dependency of `librosa` on mac os arm64.

```
- module-name: 'soundfile'
  dlls:
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile*64bit'
      when: 'win32 and arch_amd64'
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile*32bit'
      when: 'win32 and arch_x86'
    - from_filenames:
        relative_path: '_soundfile_data'
        prefixes:
          - 'libsndfile_arm64'
      when: 'macos'
```

I tried multiple variations in this section of the default.yaml and in the error message it even seems correct while ignoring my changes. 

`FATAL: Error, failed to find path @rpath/libsndfile.1.dylib (resolved DLL to /Users/bklronin/Development/venv_11/lib/python3.10/site-packages/_soundfile_data/libsndfile.1.dylib) for /Users/bklronin/Development/venv_11/lib/python3.10/site-packages/_soundfile_data/libsndfile_arm64.dylib from 'soundfile', please report the bug.`

So the thing is, the file is in place and the path seems correct but he is not recognizing the `libsndfile_arm64.dylib` and the fix was to just copy and rename it to `libsndfile.1.dylib`. 

He definitely wants his libsndfile.1.dylib :D
