### ISSUE TITLE
Error, problem with dependency scan "pyaudio"

### ISSUE THREAD

**Issue by BKLronin** [Nuitka/Nuitka#2580]
Hi!

trying to compile with pyaudio on arm64 (mac 14.1) With python 3.10. and the following packages (shortended):

PyAudio==0.2.14

1.9.1
Commercial: None
Python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/bklronin/Development/venv_11/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).

Commandline:

`python -m nuitka pyaudio_mnml.py `

Error: Appears with all python versions from 3.9 to 3.11 (CPython)

`FATAL:     Error, problem with dependency scan of '/Users/bklronin/Development/venv_11/lib/python3.10/site-packages/pyaudio/_portaudio.cpython-310-darwin.so' with '/opt/homebrew/opt/portaudio/lib/libportaudio.2.dylib' please report the bug.`

### Min example:

```
# nuitka-project: --follow-imports
# nuitka-project: --standalone
# nuitka-project: --macos-create-app-bundle

import pyaudio

p = pyaudio.PyAudio()

```

### Discussion

The correct path would be `venv_11/lib/python3.10/site-packages/_sounddevice_data/portaudio-binaries/libportaudio.dylib` but it is looking to get the present file form the system installation instead.

If I add the location via default yaml:

```
- module-name: 'pyaudio'
  dlls:
    - from_filenames:
        relative_path: '_sounddevice_data/portaudio-binaries'
        prefixes:
          - 'libportaudio64bit'
      when: 'win32 and arch_amd64'
    - from_filenames:
        relative_path: '_sounddevice_data/portaudio-binaries'
        prefixes:
          - 'libportaudio32bit'
      when: 'win32 and arch_x86'
    - from_filenames:
        relative_path: '_sounddevice_data/portaudio-binaries'
        prefixes:
          - 'libportaudio'
      when: 'macos'
```
This seems related to the issue with the 'sounddevice' module but its not a relative path problem. 

### Conclusion

I assume the lib should be searched for in the env libs folder isntead of the system folder but the yaml seems not effective in making that clear.

source path dir should be : `_sounddevice_data/portaudio-binaries` (same as sounddevice module)
source path is : `/opt/homebrew/opt/portaudio/lib/libportaudio.2.dylib ` (File is present)

P.S: Nuitka is awesome :D
