### ISSUE TITLE
Packaging Nuitka 1.9.3 for Arch Linux

### ISSUE THREAD

**Issue by xyproto** [Nuitka/Nuitka#2595]
Hi, maintainer of the `nuitka` package for Arch Linux here.

I am trying to package the latest version of `nuitka`, but some tests that previously were passing are now displaying errors.

Here is the current `PKGBUILD` file that I am working on:

```bash
pkgname=nuitka
pkgver=1.9.3
pkgrel=1
pkgdesc='Python compiler with full language support and CPython compatibility'
arch=(any)
url='https://nuitka.net/'
license=(Apache)
depends=(libxml2 patchelf python-appdirs python-setuptools python-wheel scons)
makedepends=(gdb python-build python-installer)
checkdepends=(ccache fuse2 python-boto3 python-brotli strace)
optdepends=('ccache: for build caching'
            'pyside2: for using Qt5 APIs')
source=("https://nuitka.net/releases/${pkgname^}-$pkgver.tar.bz2")
sha256sums=('ec2ed570b6c94644451c036af21508bf2f0dbf1d8ec4b4c46ed70462e51fbb9d')
b2sums=('603ed8c29b2318969b79ee55d1daa573ca4ca81de39d2a2523db3e5c09130c9446d58e1a7419fbe04cd9ea22ef6dc1237f6061260aef3413a1d49c3352eac949')

prepare() {
  cd ${pkgname^}-$pkgver
  sed -e 's,/etc/os-release,/usr/lib/os-release,' -i nuitka/utils/Utils.py
}

build() {
  cd ${pkgname^}-$pkgver
  python -m build --wheel --no-isolation
}

check() {
 cd ${pkgname^}-$pkgver/tests
 ./run-tests
}

package() {
  cd ${pkgname^}-$pkgver
  python -m installer --destdir="$pkgdir" dist/*.whl
  install -vDm 644 {Changelog,Developer_Manual,README}.rst -t "$pkgdir/usr/share/doc/$pkgname/"
}
```

And here are the errors that appears when the package is being built and `./run-tests` is being executed:

```diff
Successfully built Nuitka-1.9.3-cp311-cp311-linux_x86_64.whl
==> Starting check()...
Cannot execute tests with Python 2.6, disabled or not installed.
Cannot execute tests with Python 2.7, disabled or not installed.
Cannot execute tests with Python 2.6, disabled or not installed.
Cannot execute tests with Python 2.7, disabled or not installed.
Cannot execute tests with Python 3.3, disabled or not installed.
Cannot execute tests with Python 3.4, disabled or not installed.
Cannot execute tests with Python 3.5, disabled or not installed.
Cannot execute tests with Python 3.6, disabled or not installed.
Cannot execute tests with Python 3.7, disabled or not installed.
Cannot execute tests with Python 3.8, disabled or not installed.
Cannot execute tests with Python 3.9, disabled or not installed.
Cannot execute tests with Python 3.10, disabled or not installed.
Executing test case called 'python3.11-nodebug' with CPython 'python3.11' and extra flags ''.
Running the basic tests with options '' with 'python3.11':
Run '/usr/bin/python ./tests/basics/run_all.py search' in '/build/nuitka/src/Nuitka-1.9.3'.
Using concrete python 3.11.6 on x86_64
Comparing output of 'AssertsTest.py' using '/usr/bin/python' with flags silent, expect_success, remove_output, --nofollow-imports, --file-reference-choice=original, cpython_cache, timing, plugin_enable:pylint-warnings ...
--- /usr/bin/python (stdout)
+++ nuitka (stdout)

@@ -1,8 +0,0 @@

-Function that will assert.
-Raised <class 'AssertionError'>
-Function that will not assert.
-No exception.
-Function that will assert with argument.
-Raised <class 'AssertionError'> argument
-Assertion with tuple argument.(3,)
-Assertion with plain argument.3
--- /usr/bin/python (stderr)
+++ nuitka (stderr)

@@ -0,0 +1,9 @@

+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o: in function `loadConstantsBlob':
+/usr/include/bits/string_fortified.h:29:(.text+0xb83b): undefined reference to `constant_bin_data'
+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o: in function `loadConstantsBlob':
+/usr/src/debug/nuitka/Nuitka-1.9.3/nuitka/build/static_src/HelpersConstantsBlob.c:399:(.text+0xb84d): undefined reference to `constant_bin_data'
+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o: in function `loadConstantsBlob':
+/usr/src/debug/nuitka/Nuitka-1.9.3/nuitka/build/inline_copy/zlib/crc32.c:760:(.text+0xb8ac): undefined reference to `constant_bin_data'
+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o:/usr/src/debug/nuitka/Nuitka-1.9.3/nuitka/build/inline_copy/zlib/crc32.c:779:(.text+0xb9b2): undefined reference to `constant_bin_data'
+collect2: error: ld returned 1 exit status
+scons: *** [/var/tmp/tests-x6imf6u5/basics/python3.11-nodebug/AssertsTest.bin] Error 1
Updating CPython cache by force due to non-matching comparison results.
--- /usr/bin/python (stdout)
+++ nuitka (stdout)

@@ -1,8 +0,0 @@

-Function that will assert.
-Raised <class 'AssertionError'>
-Function that will not assert.
-No exception.
-Function that will assert with argument.
-Raised <class 'AssertionError'> argument
-Assertion with tuple argument.(3,)
-Assertion with plain argument.3
--- /usr/bin/python (stderr)
+++ nuitka (stderr)

@@ -0,0 +1,9 @@

+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o: in function `loadConstantsBlob':
+/usr/include/bits/string_fortified.h:29:(.text+0xb83b): undefined reference to `constant_bin_data'
+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o: in function `loadConstantsBlob':
+/usr/src/debug/nuitka/Nuitka-1.9.3/nuitka/build/static_src/HelpersConstantsBlob.c:399:(.text+0xb84d): undefined reference to `constant_bin_data'
+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o: in function `loadConstantsBlob':
+/usr/src/debug/nuitka/Nuitka-1.9.3/nuitka/build/inline_copy/zlib/crc32.c:760:(.text+0xb8ac): undefined reference to `constant_bin_data'
+/usr/bin/ld: /tmp/ccckZV03.ltrans2.ltrans.o:/usr/src/debug/nuitka/Nuitka-1.9.3/nuitka/build/inline_copy/zlib/crc32.c:779:(.text+0xb9b2): undefined reference to `constant_bin_data'
+collect2: error: ld returned 1 exit status
+scons: *** [/var/tmp/tests-x6imf6u5/basics/python3.11-nodebug/AssertsTest.bin] Error 1
Exit codes 0 (CPython) != 1 (Nuitka)
Error, results differed (stdout,stderr,exit_code).
Error exit! 1
==> ERROR: A failure occurred in check().
Aborting...
==> ERROR: Build failed
```

Similar errors also appear if I try these commands in the `check()` function:

```bash
rm -r programs/pkgutil_usage
./run-tests --no-other-python --skip-onefile-tests --skip-other-cpython-tests --skip-reflection-test
```

Any advice for how to making the tests pass on Arch Linux would be appreciated.

Additional info:

* This is on x86_64.
* The current CPython version on Arch Linux is `Python 3.11.6`.
* The SCons version is `4.6.0.e5eef322a4a727b96358a436dca46e8085ac8692`.

Thanks for creating and maintaining Nuitka!

**Comment by kayhayen** [comment]
Given the requested input, I would make it part of the next hotfix, can you try and provide it?

**Comment by xyproto** [comment]
Sure, here is the output from `nuitka3 --show-scons main.py` after building and installing Nuitka with the `PKGBUILD` above (sans the `check()`):

```yaml
nuitka3 --show-scons main.py
Nuitka-Options:INFO: Used command line options: --show-scons main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.3' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Scons command: /usr/bin/python -W ignore /usr/lib/python3.11/site-packages/nuitka/build/inline_copy/bi4
scons: Reading SConscript files ...
Nuitka-Scons:INFO: CC '/usr/bin/gcc' version check gives (13, 2, 1)
Nuitka-Scons:INFO: Initial CC: 'gcc'
Nuitka-Scons:INFO: Initial CCVERSION: (13, 2, 1)
Scons: Compiler used /usr/bin/gcc
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc 13.2.1).
Nuitka-Scons:INFO: LTO mode auto was resolved to mode: 'no' (not known to be supported).
Nuitka-Scons:INFO: Using C11 mode: True
Nuitka-Scons:INFO: Using resource mode: 'incbin' (default).
Nuitka-Scons:INFO: Told to run compilation on 12 CPUs.
Nuitka-Scons:INFO: Found ccache '/usr/bin/ccache' to cache C compilation result.
Nuitka-Scons:INFO: Providing real CC path '/usr/bin/gcc' via PATH extension.
Nuitka-Scons:INFO: Launching Scons target: ['/home/alexander/archpackages/extra/nuitka/main.bin']
scons: done reading SConscript files.
scons: Building targets ...
Nuitka-Scons:INFO: CC '/bin/gcc' version check gives (13, 2, 1)
"/usr/bin/ccache" "/usr/bin/gcc" -o __constants.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftracc
"/usr/bin/ccache" "/usr/bin/gcc" -o __constants_data.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -c
"/usr/bin/ccache" "/usr/bin/gcc" -o __helpers.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-c
"/usr/bin/ccache" "/usr/bin/gcc" -o __loader.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-mc
"/usr/bin/ccache" "/usr/bin/gcc" -o module.__main__.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -fc
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/MainProgram.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlic
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/CompiledFunctionType.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fparc
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available for this stage).
"/usr/bin/gcc" -o /home/alexander/archpackages/extra/nuitka/main.bin -s -z noexecstack -Wl,-R,'/usr/lib' -Wl,--disable-ne1
scons: done building targets.
Nuitka-Scons:INFO: Compiled 6 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.bin'.
```

Where `main.py` is just a simple dummy program:

```py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
```

**Comment by kayhayen** [comment]
So you are using `incbin` and not LTO mode. Can you try manually adding `--lto` and report to me if that works?

I think we should add an indicator for arch linux if that's the case, like we already have for Fedora, to recognize the fact, that we can trust it to do LTO properly. I think there is something where maybe we new gcc, `incbin` is incompatible now, not sure, but doing that optimization for Arch Linux would be good idea anyway.

**Comment by xyproto** [comment]
Using `--lto=yes` (`resource mode: 'linker'`) worked great here:

```yml
% nuitka3 --lto=yes --show-scons main.py
Nuitka-Options:INFO: Used command line options: --lto=yes --show-scons main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check
Nuitka-Options:WARNING: options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.9.3' on Python '3.11' commercial grade 'n.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Scons command: /usr/bin/python -W ignore /usr/lib/python3.11/site-packages/nui4
scons: Reading SConscript files ...
Nuitka-Scons:INFO: CC '/usr/bin/gcc' version check gives (13, 2, 1)
Nuitka-Scons:INFO: Initial CC: 'gcc'
Nuitka-Scons:INFO: Initial CCVERSION: (13, 2, 1)
Scons: Compiler used /usr/bin/gcc
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc 13.2.1).
Nuitka-Scons:INFO: Using C11 mode: True
Nuitka-Scons:INFO: Using resource mode: 'linker' (default for lto gcc with --lto bugs for incbin).
Nuitka-Scons:INFO: Told to run compilation on 12 CPUs.
Nuitka-Scons:INFO: Found ccache '/usr/bin/ccache' to cache C compilation result.
Nuitka-Scons:INFO: Providing real CC path '/usr/bin/gcc' via PATH extension.
Nuitka-Scons:INFO: Launching Scons target: ['/home/alexander/archpackages/extra/nuitka/main.bin']
scons: done reading SConscript files.
scons: Building targets ...
Nuitka-Scons:INFO: CC '/bin/gcc' version check gives (13, 2, 1)
"/usr/bin/ccache" "/usr/bin/gcc" -o __constants.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-obc
"/usr/bin/ccache" "/usr/bin/gcc" -o __helpers.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objec
"/usr/bin/ccache" "/usr/bin/gcc" -o __loader.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objecc
"/usr/bin/ccache" "/usr/bin/gcc" -o module.__main__.o -c -flto=12 -fuse-linker-plugin -fno-fat-ltc
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/MainProgram.o -c -flto=12 -fuse-linker-plugin -fnoc
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/CompiledFunctionType.o -c -flto=12 -fuse-linker-plc
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available for th.
"/usr/bin/gcc" -o /home/alexander/archpackages/extra/nuitka/main.bin -flto=12 -fuse-linker-plugin1
scons: done building targets.
Nuitka-Scons:INFO: Compiled 6 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 6
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.bin'.
```

```sh
% ./main.bin
Hello, World!
```

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by xyproto** [comment]
When using the `factory` branch, there are errors when running the tests: [stdout.log](https://github.com/Nuitka/Nuitka/files/13661954/stdout.log)

When commenting out the `check()` function in the `PKGBUILD` so that the tests are not being run, then the package builds and the executable runs. The resource mode is `incbin` by default:

```yml
% nuitka3 --version
2.0rc5
Commercial: None
Python: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None
Version C compiler: /usr/bin/gcc (gcc 13.2.1).

% nuitka3 --show-scons main.py
Nuitka-Options: Used command line options: --show-scons main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.0rc5' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Scons command: /usr/bin/python -W ignore /usr/lib/python3.11/site-packages/nuitka/build/inline_copy/bin/scons.py -f /usr/lib/python3.11/site-packages/nuitka/build/Backend.scons --jobs 12
Nuitka-Scons: --warn=no-deprecated --no-site-dir --debug=stacktrace result_name=/home/alexander/archpackages/extra/nuitka/main source_dir=. nuitka_python=false debug_mode=false python_debug=false
Nuitka-Scons: module_mode=false full_compat=false experimental= trace_mode=false file_reference_mode=original module_count=1 result_exe=/home/alexander/archpackages/extra/nuitka/main.bin
Nuitka-Scons: nuitka_src=/usr/lib/python3.11/site-packages/nuitka/build python_version=3.11 python_prefix=/usr no_deployment= show_scons=true target_arch=x86_64
scons: Reading SConscript files ...
Nuitka-Scons: CC '/usr/bin/gcc' version check gives (13, 2, 1)
Nuitka-Scons: Initial CC: 'gcc'
Nuitka-Scons: Initial CCVERSION: (13, 2, 1)
Scons: Compiler used /usr/bin/gcc
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.1).
Nuitka-Scons: LTO mode auto was resolved to mode: 'no' (not known to be supported).
Nuitka-Scons: Using C11 mode: True
Nuitka-Scons: Using resource mode: 'incbin' (default).
Nuitka-Scons: Told to run compilation on 12 CPUs.
Nuitka-Scons: Found ccache '/usr/bin/ccache' to cache C compilation result.
Nuitka-Scons: Providing real CC path '/usr/bin/gcc' via PATH extension.
Nuitka-Scons: Launching Scons target: ['/home/alexander/archpackages/extra/nuitka/main.bin']
scons: done reading SConscript files.
scons: Building targets ...
Nuitka-Scons: CC '/bin/gcc' version check gives (13, 2, 1)
"/usr/bin/ccache" "/usr/bin/gcc" -o __constants.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-inc
"/usr/bin/ccache" "/usr/bin/gcc" -o __constants_data.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleadic
"/usr/bin/ccache" "/usr/bin/gcc" -o __helpers.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indec
"/usr/bin/ccache" "/usr/bin/gcc" -o __loader.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indenc
"/usr/bin/ccache" "/usr/bin/gcc" -o module.__main__.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleadinc
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/MainProgram.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-mic
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/CompiledFunctionType.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-trackinc
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
"/usr/bin/gcc" -o /home/alexander/archpackages/extra/nuitka/main.bin -s -z noexecstack -Wl,-R,'/usr/lib' -Wl,--disable-new-dtags @"./@link_input.txt" -L/usr/lib -ldl -lm -lpython3.11
scons: done building targets.
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 6
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.bin'.

% nuitka3 --show-scons --lto=yes main.py
Nuitka-Options: Used command line options: --show-scons --lto=yes main.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.0rc5' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Scons command: /usr/bin/python -W ignore /usr/lib/python3.11/site-packages/nuitka/build/inline_copy/bin/scons.py -f /usr/lib/python3.11/site-packages/nuitka/build/Backend.scons --jobs 12
Nuitka-Scons: --warn=no-deprecated --no-site-dir --debug=stacktrace result_name=/home/alexander/archpackages/extra/nuitka/main source_dir=. nuitka_python=false debug_mode=false python_debug=false
Nuitka-Scons: module_mode=false full_compat=false experimental= trace_mode=false file_reference_mode=original module_count=1 result_exe=/home/alexander/archpackages/extra/nuitka/main.bin
Nuitka-Scons: nuitka_src=/usr/lib/python3.11/site-packages/nuitka/build python_version=3.11 python_prefix=/usr no_deployment= show_scons=true lto_mode=yes target_arch=x86_64
scons: Reading SConscript files ...
Nuitka-Scons: CC '/usr/bin/gcc' version check gives (13, 2, 1)
Nuitka-Scons: Initial CC: 'gcc'
Nuitka-Scons: Initial CCVERSION: (13, 2, 1)
Scons: Compiler used /usr/bin/gcc
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.1).
Nuitka-Scons: Using C11 mode: True
Nuitka-Scons: Using resource mode: 'linker' (default for lto gcc with --lto bugs for incbin).
Nuitka-Scons: Told to run compilation on 12 CPUs.
Nuitka-Scons: Found ccache '/usr/bin/ccache' to cache C compilation result.
Nuitka-Scons: Providing real CC path '/usr/bin/gcc' via PATH extension.
Nuitka-Scons: Launching Scons target: ['/home/alexander/archpackages/extra/nuitka/main.bin']
scons: done reading SConscript files.
scons: Building targets ...
Nuitka-Scons: CC '/bin/gcc' version check gives (13, 2, 1)
"/usr/bin/ccache" "/usr/bin/gcc" -o __constants.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecatedc
"/usr/bin/ccache" "/usr/bin/gcc" -o __helpers.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-dc
"/usr/bin/ccache" "/usr/bin/gcc" -o __loader.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-dec
"/usr/bin/ccache" "/usr/bin/gcc" -o module.__main__.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecc
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/MainProgram.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wnoc
"/usr/bin/ccache" "/usr/bin/gcc" -o static_src/CompiledFunctionType.o -c -flto=12 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansic
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
"/usr/bin/gcc" -o /home/alexander/archpackages/extra/nuitka/main.bin -flto=12 -fuse-linker-plugin -fpartial-inlining -freorder-functions -O3 -s -z noexecstack -Wl,-R,'/usr/lib' -Wl,--disable-new-dtags -Wl,-1
scons: done building targets.
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 5
Nuitka: Keeping build directory 'main.build'.
Nuitka: Successfully created 'main.bin'.
```
