### ISSUE TITLE
How to install with pip in GitHub workflows

### ISSUE THREAD

**Issue by pcdd-group** [Nuitka/Nuitka#2615]
```yaml
name: Example Workflow

on: [push]

jobs:
  example_job:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install nuitka
```

After executing `pip install nuitka`, you need to enter Yes or No halfway to download mingw64 and Dependency Walker. How can I input it automatically?
