### ISSUE TITLE
Problem with skimage lazy loader import not working for `from ..filters import sobel` in `skimage.segmentation.active_contour_model`

### ISSUE THREAD

**Issue by KevinRodriguez777** [Nuitka/Nuitka#2680]
```
2.1rc1
Commercial: None
Python: 3.10.13 (main, Jan  3 2024, 21:05:13) [GCC 11.4.0]
Flavor: pyenv
Executable: /home/divine/Nuitka-Testing/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc 11).
```
MRE
```
from paddleocr import PaddleOCR # type: ignore
import sys
import os
engine = PaddleOCR(use_angle_cls=True, lang="en", use_gpu=False)
output = engine.ocr('one.jpg')
for res in output[0]:
    print(res[1][0])
```
(use any image with text on it for the example)
requirements
```
anyio==4.2.0
astor==0.8.1
attrdict==2.0.1
Babel==2.14.0
bce-python-sdk==0.8.98
beautifulsoup4==4.12.2
blinker==1.7.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.2.0
cssselect==1.2.0
cssutils==2.9.0
cycler==0.12.1
Cython==3.0.7
decorator==5.1.1
et-xmlfile==1.1.0
exceptiongroup==1.2.0
fire==0.5.0
Flask==3.0.0
flask-babel==4.0.0
fonttools==4.47.0
future==0.18.3
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
imageio==2.33.1
imgaug==0.4.0
itsdangerous==2.1.2
Jinja2==3.1.2
kiwisolver==1.4.5
lazy_loader==0.3
lmdb==1.4.1
lxml==5.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
networkx==3.2.1
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip#sha256=eb265ab70932e9e3d195e1a92f00efce979501537c2bdc971c62fa88951aa312
numpy==1.26.3
opencv-contrib-python==4.6.0.66
opencv-python==4.6.0.66
openpyxl==3.1.2
opt-einsum==3.3.0
ordered-set==4.1.0
packaging==23.2
paddleocr==2.7.0.3
paddlepaddle==2.6.0
paddlepaddle-gpu==2.6.0
pandas==2.1.4
pdf2docx==0.5.6
pillow==10.2.0
premailer==3.10.0
protobuf==4.25.1
psutil==5.9.7
pyclipper==1.3.0.post5
pycryptodome==3.19.1
PyMuPDF==1.20.2
pyparsing==3.1.1
python-dateutil==2.8.2
python-docx==1.1.0
pytz==2023.3.post1
PyYAML==6.0.1
rapidfuzz==3.6.1
rarfile==4.1
requests==2.31.0
scikit-image==0.22.0
scipy==1.11.4
shapely==2.0.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
termcolor==2.4.0
tifffile==2023.12.9
tqdm==4.66.1
typing_extensions==4.9.0
tzdata==2023.4
urllib3==2.1.0
visualdl==2.5.3
Werkzeug==3.0.1
zstandard==0.22.0
```
if you're having problems with paddle install it from https://www.paddlepaddle.org.cn/

**Comment by KevinRodriguez777** [comment]
```
- module-name: "paddle"
  dlls:
    - from_filenames:
        relative_path: "libs"
        prefixes:
          - "lib"
          - "mkl"
          - "war"
          - "common"

- module-name: "paddleocr"
  implicit-imports:
    - depends:
        - "PIL"
        - "PIL.Image"
        - "PIL.ImageDraw"
        - "PIL.ImageFont"
        - "shapely"
        - "scipy.cluster.vq"
        - "skimage"
        - "imageio"
        - "imgaug"
        - "pyclipper"
        - "paddleocr.ppocr"
        - "paddleocr.ppstructure"
        - "paddleocr.ppocr.utils"

- module-name: "paddle.fluid.core"
  anti-bloat:
    replacements_plain:
      "third_lib_path = current_path + os.sep + '..' + os.sep + 'libs'": "third_lib_path = os.path.normpath(current_path + os.sep + '..' + os.sep + 'libs')"
      "set_paddle_lib_path()": ""

- module-name: "paddle.base.core"
  anti-bloat:
    replacements_plain:
      "third_lib_path = current_path + os.sep + '..' + os.sep + 'libs'": "third_lib_path = os.path.normpath(current_path + os.sep + '..' + os.sep + 'libs')"
      "def set_paddle_lib_path():": ""
      "set_paddle_lib_path()": ""

- module-name: "paddleocr.paddleocr"
  anti-bloat:
    replacements_plain:
      "tools = _import_file(": ""
      "    'tools', os.path.join(__dir__, 'tools/__init__.py'), make_importable=True)": "from . import tools"
  import-hacks:
    - global-sys-path:
        # This package forces itself into "sys.path" and expects absolute
        # imports to be available.
        - ""
- module-name: "paddleocr.ppocr.tools.utils.e2e_utils.pgnet_pp_utils"
  anti-bloat:
    replacements_plain:
      "from extract_textpoint_slow import *": "from .extract_textpoint_slow import *"
      "from extract_textpoint_fast import generate_pivot_list_fast, restore_poly": "from .extract_textpoint_fast import generate_pivot_list_fast, restore_poly"
    import-hacks:
      - global-sys-path:
          # This package forces itself into "sys.path" and expects absolute
          # imports to be available.
          - ""
- module-name: "ppocr.utils.e2e_utils.pgnet_pp_utils"
  anti-bloat:
    replacements_plain:
      "from extract_textpoint_slow import *": "from .extract_textpoint_slow import *"
      "from extract_textpoint_fast import generate_pivot_list_fast, restore_poly": "from .extract_textpoint_fast import generate_pivot_list_fast, restore_poly"
    import-hacks:
      - global-sys-path:
          # This package forces itself into "sys.path" and expects absolute
          # imports to be available.
          - ""
```
this YAML config is needed to reproduce the issue, it's the last entry: `ppocr.utils.e2e_utils.pgnet_pp_utils` according to some trial and error that causes the segfault.

**Comment by kayhayen** [comment]
You kept me too busy to look at this, lol

**Comment by kayhayen** [comment]
I am wondering, if it's a good strategy to try and not have your full yaml config immediately, and see how much of it comes up for me, but I guess this might be a too slow compile for that to be worth it.

**Comment by kayhayen** [comment]
Since we are not on a timer, i.e. do have to be as quick as possible, let me try that until I get fed up with it, lol. I think I noticed this one makes sense:

```
- module-name: 'fire.interact' # checksum: 7d07a2d1
  anti-bloat:
    - description: 'remove IPython reference'
      no-auto-follow:
        'IPython': 'ignore'
      when: 'not use_ipython'
```
