### ISSUE TITLE
Need to support "aspose"

### ISSUE THREAD

**Issue by KevinRodriguez777** [Nuitka/Nuitka#2713]
> python -m nuitka --version
```
2.0.2
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Divine\Desktop\PyDis\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
- How did you install Nuitka and Python
cpython / pip install

  > python -m pip freeze

you'll need to pip install `Aspose.Email-for-Python-via-NET`

- Also supply a Short, Self Contained, Correct, Example
```
from aspose.email.mapi import MapiMessage
# from aspose.email import mapi

def main():
    msg = mapi.MapiMessage.load(r"testing.eml")
    print("Subject:", msg.subject)
    print("From:", msg.sender_email_address)


if __name__ == "__main__":
    main()
```
with the commented code available it will work when compiled
- Provide in your issue the Nuitka options used
`nuitka --standalone main.py`

**Comment by kayhayen** [comment]
I am assuming I will need yaml config for this one too, right?

**Comment by kayhayen** [comment]
Seems this is what is needed:

```
- module-name: 'aspose.email'
  dlls:
    - from_filenames:
        prefixes:
          - 'email'
          - 'pycore'
          - 'pygc'
          - 'pyreflection'
        suffixes:
          - 'pyd'
      when: 'win32'
    - from_filenames:
        relative_path: 'assemblies/email'
        prefixes:
          - 'Aspose'
          - 'System'
          - 'WrpInterop'
      when: 'win32'
    - from_filenames:
        relative_path: 'assemblies/pycore'
        prefixes:
          - 'WrpInterop'
      when: 'win32'
    - from_filenames:
        relative_path: 'assemblies/pygc'
        prefixes:
          - 'Aspose'
      when: 'win32'
    - from_filenames:
        relative_path: 'assemblies/pyreflection'
        prefixes:
          - 'WrpInterop'
      when: 'win32'
    - from_filenames:
        relative_path: 'netcore/netcore3.1'
        prefixes:
          - 'aspose'
          - 'System'
          - 'api-ms-win'
          - 'Microsoft'
          - 'mscor'
          - 'ucrtbase'
          - 'WindowsBase'
          - 'netstandard'
          - 'host'
          - 'dbgshim'
          - 'clr'
          - 'coreclr'
      when: 'win32'
```

**Comment by kayhayen** [comment]
That looks horribly wrong:

```
- module-name: 'aspose.email'
  dlls:
    - from_filenames:
        prefixes:
          - 'email'
          - 'pycore'
          - 'pygc'
          - 'pyreflection'
        suffixes:
          - 'pyd'
      when: 'win32'
```

Given that `email` is the one making the trouble, I wonder how that happens, but that looks like a poor DLL configuration or a very poor upstream. I think "email" will slash will "email", maybe therefore not being something to import from anymore?

**Comment by kayhayen** [comment]
That's how these seem to be done correctly, not getting all you had there:

```
- module-name: 'aspose.email'
  implicit-imports:
    - depends:
        - 'aspose.pyreflection'
        - 'aspose.pygc'
```

DLLs with "pyd" suffix should *only* be used when it is *not* an importable module. Doing them as DLLs is defeating the ability of Nuitka to import things, as it will not know that it's an extension module.
