### ISSUE TITLE
Gruut compile issue

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2763]
Fails to find packages for gruut also a known problem with pyinstaller
 
# ImportError: cannot import name _dumpparser
https://gist.github.com/luisdelatorre012/db61b489acadf3e42f217597c5392bf8

2.1.1
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]   
Flavor: CPython Official
Executable: C:\Users\Tensor\Desktop\WaifuEngineProjects\Cut-StyleTTS2\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Problem:
Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\example.py", line 1, in <module>
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\StyleTTS\StyleTTS2.py", line 14, in <module StyleTTS.StyleTTS2>
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\gruut\__init__.py", line 13, in <module gruut>
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\gruut\text_processor.py", line 45, in <module gruut.text_processor>
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\gruut\lang.py", line 12, in <module gruut.lang>
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\gruut\g2p.py", line 44, in <module gruut.g2p>
  File "C:\Users\Tensor\Desktop\WA0DCA~1\CUT-ST~1\EXAMPL~1.DIS\pycrfsuite\__init__.py", line 2, in <module pycrfsuite>
  File "pycrfsuite/_pycrfsuite.pyx", line 14, in init pycrfsuite._pycrfsuite
ImportError: cannot import name _dumpparser

  > python -m pip freeze
Babel==2.14.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
dateparser==1.1.8
docopt==0.6.2
einops==0.7.0
einops-exts==0.0.4
filelock==3.9.0
fsspec==2024.2.0
gruut==2.3.4
gruut-ipa==0.13.0
gruut-lang-en==2.0.0
huggingface-hub==0.21.4
idna==3.6
Jinja2==3.1.2
joblib==1.3.2
jsonlines==1.2.0
MarkupSafe==2.1.3
monotonic_align @ git+https://github.com/resemble-ai/monotonic_align.git@78b985be210a03d08bc3acc01c4df0442105366f
mpmath==1.3.0
networkx==2.8.8
nltk==3.8.1
Nuitka==2.1.1
num2words==0.5.13
numpy==1.26.3
ordered-set==4.1.0
packaging==24.0
pillow==10.2.0
pycparser==2.21
python-crfsuite==0.9.10
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
safetensors==0.4.2
six==1.16.0
soundfile==0.12.1
sympy==1.12
tokenizers==0.15.2
torch==2.2.1+cu121
torchaudio==2.2.1+cu121
torchvision==0.17.1+cu121
tqdm==4.66.2
transformers==4.38.2
typing_extensions==4.8.0
tzdata==2024.1
tzlocal==5.2
urllib3==2.2.1
zstandard==0.22.0

- Also supply a Short, Self Contained, Correct, Example
install this 
gruut==2.3.4
gruut-ipa==0.13.0
gruut-lang-en==2.0.0
```
from gruut import sentences

def phonemizer(self, text):
        phonemized = []
        for sent in sentences(text, lang="en-us", espeak=True):
            for word in sent:
                if word.phonemes:
                    phonemized.append(''.join(word.phonemes))
        return [' '.join(phonemized)]
```
 default nuitka build command

**Comment by KevinRodriguez777** [comment]
@kayhayen can you give this a try?
```yaml
- module-name: 'pycrfsuite'
  implicit-imports:
    - depends:
      - 'pycrfsuite._dumpparser'
      - 'pycrfsuite._logparser'

  dlls:
    - from_filenames:
        prefixes:
          - '_pycrfsuite'

- module-name: "gruut"
  implicit-imports:
    - depends:
      - "gruut_ipa"
      - "gruut_lang_en"
  data-files:
    patterns:
      - 'VERSION'
    
- module-name: "gruut_ipa"
  data-files:
    dirs:
      - 'espeak'
      - 'g2p'
      - 'pos'
    patterns:
      - "VERSION"
      - "lexicon.db"


- module-name: "gruut_lang_en"
  data-files:
    dirs:
      - 'data'
 ```
the issue is the inclusion of needed data files for gruut
