### ISSUE TITLE
pyuac support

### ISSUE THREAD

**Issue by KRRT7** [Nuitka/Nuitka#2776]
requirements
`pip install pyuac pywin32`
code

```py

import pyuac

if not pyuac.isUserAdmin():
    pyuac.runAsAdmin()
```
when compiled we get this
![image](https://github.com/Nuitka/Nuitka/assets/106575910/5e652ba2-ccb1-4ee5-a98d-19a2bdcbe109)
since it tries to find python.exe

**Comment by kayhayen** [comment]
Any progress on this one @KevinRodriguez777 it seems easy I think, just needs to identify the function that does the elevation and use `change_function` on it. If you feel the docs are lacking for that to be actually easily doable, let me know.

**Comment by kayhayen** [comment]
Seems nobody is doing this, so I stepped up to do it:

```
Nuitka: Launching 'Mini.dist\Mini.exe'.
Traceback (most recent call last):
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\Mini.py", line 5, in <module>
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\pyuac\admin.py", line 1, in runAsAdmin
RuntimeError: Nuitka: Needs to be elevated already, use --windows-uac-admin
```

This is the final config:

```
- module-name: 'pyuac.admin' # checksum: 7039cb00
  anti-bloat:
    - change_function:
        'runAsAdmin': "'''raise RuntimeError('Nuitka: Needs to be elevated already, use --windows-uac-admin')'''"
```

It's only the second time we got this, so I am not going to add it. Will be coming to factory once I stabilize other changes I have going on right now, setting the tag early therefore, just so I don't forget an issue nobody is looking at anyway apparently.
