### ISSUE TITLE
Error while compiling project with Yaml config file

### ISSUE THREAD

**Issue by RobertAzovski** [Nuitka/Nuitka#2803]
Command used:

> $ python -m nuitka --remove-output --mingw64 --windows-icon-from-ico=icon.ico --standalone --onefile --user-package-configuration-file=mainconfigfile.yaml mmCheckAddress.py

Yaml file:
```
- module-name: 'tls_client.cffi'

dlls:
   - from_filenames:
      relative_path: 'dependencies'
      prefixes:
         - 'tls-client'
      suffixes:
         - 'dll'
      when: 'win32'
   - from_filenames:
      relative_path: 'dependencies'
      prefixes:
         - 'tls-client'
      suffixes:
         - 'so'
      when: 'linux'
   - from_filenames:
      relative_path: 'dependencies'
      prefixes:
         - 'tls-client'
      suffixes:
         - 'dylib'
      when: 'macos'
```
      
Traceback:

> Nuitka-Options: Used command line options: --remove-output --mingw64 --windows-icon-from-ico=icon.ico --standalone --onefile
Nuitka-Options: --user-package-configuration-file=mainconfigfile.yaml main.py
Traceback (most recent call last):
  ...
  ```
yaml.parser.ParserError: while parsing a block collection
  in "<byte string>", line 1, column 1:
    - module-name: 'tls_client.cffi'
    ^
expected <block end>, but found '?'
  in "<byte string>", line 3, column 1:
    dlls:
    ^
```
AssertionError
FATAL: anti-bloat: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.
