### ISSUE TITLE
I encountered a problem with file overwriting when using LTO=yes

### ISSUE THREAD

**Issue by Xingsandesu** [Nuitka/Nuitka#2875]
## I encountered a problem with file overwriting when using LTO=yes
```
Nuitka version: 2.2.3
Linux version: Debian12.5
Python version: 3.11
Build command: python3 -m nuitka --follow-imports --standalone --show-scons --lto=yes --static-libpython=yes --include-package=uvicorn,gunicorn,pydantic,logging --output-dir =build/app.dist app.py
```
```
(.venv) root@erp:~/Zero_ERP# python -m nuitka --version
2.2.3
Commercial: None
Python: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Flavor: Debian Python
Executable: /root/Zero_ERP/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 12
Version C compiler: /usr/bin/gcc (gcc 12).
```
## How did you install Nuitka and Python
I used the Python environment that comes with Debian and installed the virtual environment created by Python-Venv using Apt.

## Question code:
```
DEFAULT_CONFIG = {....}
#The above is the code that defines the default configuration
# Problem code load_config
def load_config():
     try:
         with open('config.yaml', 'r') as file:
             config = yaml.safe_load(file)
     exceptException:
         key = jwk.JWK.generate(kty='RSA', size=4096)
         DEFAULT_CONFIG['PRIVATE_KEY_JSON'] = key.export_private()
         DEFAULT_CONFIG['PUBLIC_KEY_JSON'] = key.export_public()
         config=DEFAULT_CONFIG
         with open('config.yaml', 'w') as file:
             yaml.dump(DEFAULT_CONFIG, file)
     return config
#The following is the code to read the configuration and save it as a constant
CONFIG = load_config()
HOST = CONFIG['HOST']
```

## Details of the problem encountered:
I use FastApi to build the backend of my web application. When I write my program, I need to read the relevant configuration information from config.yaml, so I use open to open the Yaml file, but when I enable LTO =Yes, this configuration file will be read and written repeatedly. For example, I have modified my configuration file now. When the LTO-optimized program is running, it will not read the contents of the file, but will overwrite and write the configuration file. As a result, all configurations of the program will not be used. When I turn off LTO optimization, the problem is solved. Another strange phenomenon is that when I use logging or print methods to output Chinese characters, using LTO optimization will convert the Chinese characters into Unicode encoding for output.

The above are the problems I encountered when using Nuitka. Nuitka is a good project, and I would like to thank all developers for their efforts. I hope this project gets better and better

**Comment by Xingsandesu** [comment]
我想我应该去捕获这个异常，请稍等我去查看这个异常输出信息

**Comment by Xingsandesu** [comment]
I think I should catch this exception. Please wait a moment while I check the output information of this exception.

**Comment by Xingsandesu** [comment]
The Unicode code is Chinese, and the translated meaning is "Enterprise WeChat configuration error, please check the relevant configuration of Enterprise WeChat." Because the relevant configurations of Enterprise WeChat are stored in config.yaml, the error reported ultimately is the code for loading config above. 'ascii' codec can't decode byte 0xe6 in position 146: ordinal not in range(128)
```
root@erp:~/test# ./app.bin 
'ascii' codec can't decode byte 0xe6 in position 146: ordinal not in range(128)
\u4f01\u4e1a\u5fae\u4fe1\u914d\u7f6e\u9519\u8bef\uff0c\u8bf7\u68c0\u67e5\u4f01\u4e1a\u5fae\u4fe1\u76f8\u5173\u914d\u7f6e
Traceback (most recent call last):
  File "/root/test/app.py", line 18, in <module>
ImportError: cannot import name 'wechat_push' from 'ext.ext' (/root/test/ext/ext.py)
```
error code: 
`'ascii' codec can't decode byte 0xe6 in position 146: ordinal not in range(128)`

**Comment by Xingsandesu** [comment]
In my testing, this is a possible fix: specify UTF-8 encoding, but I still don't understand why this problem will not occur without turning on LTO optimization.
```
def load_config():
    try:
        with open('config.yaml', 'r', encoding='utf-8') as file:
            config = yaml.safe_load(file)
    except Exception as e:
        # Generate a new key pair
        print(e)
        key = jwk.JWK.generate(kty='RSA', size=4096)

        # Export the private key and public key
        DEFAULT_CONFIG['PRIVATE_KEY_JSON'] = key.export_private()
        DEFAULT_CONFIG['PUBLIC_KEY_JSON'] = key.export_public()

        config = DEFAULT_CONFIG
        with open('config.yaml', 'w', encoding='utf-8') as file:
            yaml.dump(DEFAULT_CONFIG, file)

    return config
```

**Comment by kayhayen** [comment]
The default encoding is `sys.getfilesystemencoding()`. Maybe print it in compiled variants of your system and see if there is a difference. I doubt there would be a difference.

**Comment by Xingsandesu** [comment]
> The default encoding is `sys.getfilesystemencoding()`. Maybe print it in compiled variants of your system and see if there is a difference. I doubt there would be a difference.

   Thank you very much for your suggestion, I added sys.getfilesystemencoding() to test run. The following is the modified code.
As you can see from the program output below, using LTO optimization, the default will become **ascii** instead of **UTF-8**. 
   This may be the reason why Chinese characters become Unicode, and it may also be the cause of the error **'ascii' codec can't decode byte 0xe6 in position 146: ordinal not in range(128) reason**
   In addition, I will attach the log of Github Action. This example is compiled with Github Action. After my testing, whether using local Debian12 using nuitka installed with pip or using Github Action directly, this problem always exists.
[job-logs.txt](https://github.com/Nuitka/Nuitka/files/15396858/job-logs.txt)

```
def load_config():
    try:
        systemencoding = sys.getfilesystemencoding()
        print(f"Load_Config_Nomal:{systemencoding}")
        with open('config.yaml', 'r') as file:
            config = yaml.safe_load(file)
    except Exception as e:
        # Generate a new key pair
        systemencoding = sys.getfilesystemencoding()
        print(f"Load_Config_Exception:{systemencoding}")
        print(e)
        key = jwk.JWK.generate(kty='RSA', size=4096)

        # Export the private key and public key
        DEFAULT_CONFIG['PRIVATE_KEY_JSON'] = key.export_private()
        DEFAULT_CONFIG['PUBLIC_KEY_JSON'] = key.export_public()

        config = DEFAULT_CONFIG
        with open('config.yaml', 'w') as file:
            yaml.dump(DEFAULT_CONFIG, file)

    return config
```
## lto=yes
```
root@erp:~/ltoyes-18# ./app.bin 
Load_Config_Nomal:ascii
Load_Config_Exception:ascii
'ascii' codec can't decode byte 0xe6 in position 146: ordinal not in range(128)
\u4f01\u4e1a\u5fae\u4fe1\u914d\u7f6e\u9519\u8bef\uff0c\u8bf7\u68c0\u67e5\u4f01\u4e1a\u5fae\u4fe1\u76f8\u5173\u914d\u7f6e
Traceback (most recent call last):
  File "/root/ltoyes-18/app.py", line 18, in <module>
ImportError: cannot import name 'wechat_push' from 'ext.ext' (/root/ltoyes-18/ext/ext.py)
```
## Use Cpython directly and lto=no
```
Load_Config_Nomal:utf-8
[2024-05-22 08:50:33 +0800] [2708] [INFO] Starting gunicorn 22.0.0
[2024-05-22 08:50:33 +0800] [2708] [INFO] Listening at: http://127.0.0.1:8000 (2708)
[2024-05-22 08:50:33 +0800] [2708] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-05-22 08:50:33 +0800] [2725] [INFO] Booting worker with pid: 2725
[2024-05-22 08:50:33 +0800] [2725] [INFO] Started server process [2725]
[2024-05-22 08:50:33 +0800] [2725] [INFO] Waiting for application startup.
[2024-05-22 08:50:33 +0800] [2725] [INFO] Application startup complete.
[2024-05-22 08:50:33 +0800] [2727] [INFO] Booting worker with pid: 2727
[2024-05-22 08:50:33 +0800] [2727] [INFO] Started server process [2727]
```
```
Load_Config_Nomal:utf-8
Load_Config_Exception:utf-8
[Errno 2] No such file or directory: 'config.yaml'
企业微信配置错误，请检查企业微信相关配置
Traceback (most recent call last):
  File "/root/Zero_ERP/app.py", line 18, in <module>
    from ext.ext import wechat_push
ImportError: cannot import name 'wechat_push' from 'ext.ext' (/root/Zero_ERP/ext/ext.py)
```
## Github Action
```
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app.py
          company-name: KooKoo.top
          product-name: ZERO_ERP
          file-version: ${{ github.ref_name }}
          product-version: ${{ github.ref_name }}
          standalone: true
          show-scons: true
          onefile: false
          static-libpython: yes
          lto: yes
          include-package: | 
                    uvicorn
                    gunicorn
                    pydantic
                    logging
          
```
