### ISSUE TITLE
Error, failed to evaluate condition 'no_docstrings and no_asserts' in this context, exception was ''NuitkaPluginAntiBloat' object has no attribute 'decideAssertions'

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#3038]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

2.4.4
Commercial: None
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\sebastiano.manfredin\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python

Installed using pip

- The specific PyPI names and versions

scikit-learn                 1.2.2
xgboost                      2.1.1
numba                        0.56.2
numpy                        1.23.2
imbalanced-learn             0.12.3

- Provide in your issue the Nuitka options used

--python-flag=-OO --nofollow-import-to=tensorflow,keras,matplotlib,botocore --noinclude-numba-mode=nofollow --noinclude-dask-mode=nofollow --noinclude-IPython-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-setuptools-mode=nofollow --output-filename=test.exe --remove-output   --onefile

- Note if this is a regression

This is a regression, with nuitka version 2.1.4 everything was working fine

Here you can find the [compilation-report.zip](https://github.com/user-attachments/files/16451408/compilation-report.zip)

## Explanation

I have updated nuitka from version 2.1.4 to the latest and my compilation has stopped working. I dont have a specific reproducer beacause the error does not say anything about where it fails and it seems more related to nuitka itself and the management of the -OO python flag that removes assertions and docstring

**Comment by interseba5** [comment]
Investigating a bit further i think the error is somehow related to the xgboost package (that i use) and this config in standard.nuitka-package.config.yml:
```yaml
- module-name: 'xgboost.sklearn' # checksum: 5480616e
  anti-bloat:
    - description: 'remove docstring dependency'
      replacements_plain:
        'fit.__doc__ = XGBModel.fit.__doc__.replace(': 'fit.__doc__ = "Fit gradient boosting model".replace('
      when: 'no_docstrings and no_asserts'
```
I think this because this is the only configuration with both no_docstrings and no_asserts and the error says failed to evaluate condition 'no_docstrings and no_asserts'
