### ISSUE TITLE
Sklearn missing .libs folder after compiling on newest windows-2022 github actions runner

### ISSUE THREAD

**Issue by jdrubin91** [Nuitka/Nuitka#3115]
Hi there,

I'm having the same issue reported here: https://github.com/Nuitka/Nuitka/issues/1544 . I am using Nuitka within a github action that was working a couple of weeks ago. It seems that recently github has updated their runner images so potentially that is part of the issue (https://github.com/actions/runner-images/releases). Here is the requested information for issue reporting:

Nuitka was installed and run using the github action: https://github.com/Nuitka/Nuitka-Action/tree/main

 > python -m nuitka --version
```
2.4.8
Commercial: None
Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\hostedtoolcache\windows\Python\3.12.5\x64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```

 > python -m pip list -v
```
Package       Version Location                                                       Installer
------------- ------- -------------------------------------------------------------- ---------
joblib        1.4.2   C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
Nuitka        2.4.8   C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
numpy         2.1.1   C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
ordered-set   4.1.0   C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
pip           24.2    C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
scikit-learn  1.5.1   C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
scipy         1.14.1  C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
threadpoolctl 3.5.0   C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
wheel         0.38.4  C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
zstandard     0.20.0  C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\site-packages pip
```

Code example (`sklearn_test.py`):
```
import sklearn
from sklearn.metrics import r2_score
a = [1,2,3]
b = [3,4,5]
print(r2_score(a,b))
print("hello world!")
```

build.yml used with github actions:
```
name: Build for Windows with Nuitka

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12.5'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip install scikit-learn==1.5.1

    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: sklearn_test.py
        onefile: false
        standalone: true
    
    - name: Get Nuitka info
      run: |
        python -m nuitka --version
        python -m pip list -v

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: build/sklearn_test.dist
```

Full error output:
```
C:\Users\jdrubin\Downloads\dist>sklearn_test.exe Traceback (most recent call last): 
File "C:\Users\JDRUBI~1\DOWNLO~1\dist\sklearn_test.py", line 1, in <module> 
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load 
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked 
File "C:\Users\JDRUBI~1\DOWNLO~1\dist\sklearn\__init__.py", line 80, in <module sklearn> 
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load 
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked 
File "C:\Users\JDRUBI~1\DOWNLO~1\dist\sklearn\_distributor_init.py", line 21, in <module sklearn._distributor_init> 
File "C:\Users\JDRUBI~1\DOWNLO~1\dist\ctypes\__init__.py", line 379, in __init__ 
FileNotFoundError: Could not find module 'C:\Users\JDRUBI~1\DOWNLO~1\dist\sklearn\.libs\vcomp140.dll' (or one of its dependencies). 
Try using the full path with constructor syntax. C:\Users\jdrubin\Downloads\dist>
```
Note: The entire `.libs` folder is absent from `dist/sklearn`

Please let me know if I can provide any more information or assistance with resolving this issue.
