### ISSUE TITLE
Cannot use both '--mode=' and deprecated options that specify mode.

### ISSUE THREAD

**Issue by Erriez** [Nuitka/Nuitka#3237]
Github Action building a [Python release build](https://github.com/Erriez/midi-sysex-io/actions/runs/12125747829) generates the following failure for both Linux and Windows:

```
Successfully installed nuitka-2.5.5
...
Nuitka-Options: Used command line options: --output-dir=. --output-file=erriez-midi-sysex-io-linux --include-data-dir=images=images --include-data-dir=data=data --standalone --onefile --mode=app --assume-yes-for-downloads --script-name=main.py --enable-plugins=pyside6
FATAL: Cannot use both '--mode=' and deprecated options that specify mode.
```

Github action build config: [build-release.yml](https://github.com/Erriez/midi-sysex-io/actions/runs/12125747829/workflow#L78)
```yaml
      - name: Build Linux executable
        if: runner.os == 'Linux'
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          output-dir: .
          output-file: erriez-midi-sysex-io-linux
          include-data-dir: |
            images=images
            data=data
          standalone: true
          onefile: true
          enable-plugins: pyside6
```

```yaml
      - name: Build Windows executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          output-dir: .
          output-file: erriez-midi-sysex-io.exe
          include-data-dir: |
            images=images
            data=data
          standalone: true
          onefile: true
          disable-console: true
          windows-icon-from-ico: images/midi.ico
          enable-plugins: pyside6
```

Buildlog: https://github.com/Erriez/midi-sysex-io/actions/runs/12125747829

> `FATAL: Cannot use both '--mode=' and deprecated options that specify mode.`

The error message is unclear. If this mode cannot be used anymore, where is documented how to migrate existing projects to resolve this problem?

**Comment by fizzi01** [comment]
Funny thing; 1h ago was woking perfectly....

**Comment by Erriez** [comment]
- Last successful run: [28 October 2024 nuitka-2.4.11](https://github.com/Erriez/midi-sysex-io/actions/runs/11782786112/job/32818582217)
- First build error: [16 November 2024 nuitka-2.5](https://github.com/Erriez/midi-sysex-io/actions/runs/11871234782/job/33083511701)

No project source modifications.

**Comment by fizzi01** [comment]
I can confirm that it still works without using "standalone" and/or "onefile" on Nuitka 2.5.5. 
Tested on Windows and OSX.

PS: On windows is working with `mode: standalone`

**Comment by Erriez** [comment]
Reproducible testcase on a Linux desktop (repeating commands from Github Action):

```
$ git clone git@github.com:Erriez/midi-sysex-io.git
$ cd midi-sysex-io/
$ virtualenv venv
$ . venv/bin/activate
$ pip install -r requirements.txt
$ pip install nuitka

$ nuitka --version
2.5.4
Commercial: None
Python: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
Flavor: Debian Python
Executable: ~/src/midi-sysex-io/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 24.04.1
Version C compiler: /usr/bin/gcc (gcc 13).

$ nuitka --output-dir=. --output-file=erriez-midi-sysex-io-linux --include-data-dir=images=images --include-data-dir=data=data --standalone --onefile --mode=app --assume-yes-for-downloads --script-name=main.py --enable-plugins=pyside6

Nuitka-Options: Used command line options: --output-dir=. --output-file=erriez-midi-sysex-io-linux
Nuitka-Options: --include-data-dir=images=images --include-data-dir=data=data --standalone --onefile --mode=app
Nuitka-Options: --assume-yes-for-downloads --script-name=main.py --enable-plugins=pyside6
FATAL: Cannot use both '--mode=' and deprecated options that specify mode.
```

**Comment by Erriez** [comment]
https://nuitka.net/changelog/Changelog.html#new-features
```
UI: Introduced a new --mode selector to replace the options --standalone, --onefile, --module, and --macos-create-app-bundle.
```

And: https://github.com/Nuitka/Nuitka-Action/releases

> This adds support for 2.5 new option mode, that shall be used over standalone, module or onefile options in the future.

Where is this migration of Github Action yaml file to Nuitka 2.5 documented?

**Comment by fizzi01** [comment]
> What should I do to fix my project?

remove old standalone and onefile and just use 
`mode: standalone` or `--mode=standalone`

Reading https://nuitka.net/changelog/Changelog.html#new-features, you should replace both `--standalone --onefile` with `--mode=app`

**Comment by Erriez** [comment]
Thanks for your suggestion, but does not work:

- Changes in https://github.com/Erriez/midi-sysex-io/commit/c647fe3a01e9e6ebca37c5702d41c9611d8c4f39
- Buiild log: https://github.com/Erriez/midi-sysex-io/actions/runs/12128015446/job/33813517416

I've now set Nuitka to a fixed previous working version 2.4.11 and Github Nuitka-Action to v1.1. I don't want to get bothered by silent Nuitka API or command line changes where the error should be reverse engineered. Was this breaking API change really necessary? I do not see the value other than wasting time on fixing my projects.

I consider to replace Nuitka by another full open source tool which is non-commercial.

Closing ticket. I will not spend more time on this issue.

**Comment by fizzi01** [comment]
Strange... I see that in the build log, Nuitka automatically inserts `--onefile` even if in the file .yml is not specified...
Checking your log as soon as Nuitka-Actions invokes, automatically inserts 'onefile: true', it could be a git actions cache issue.

Your log:
```
Run Nuitka/Nuitka-Action@v1.2
  with:
    nuitka-version: [2](https://github.com/Erriez/midi-sysex-io/actions/runs/12128015446/job/33813517416#step:9:2).5.5
    script-name: main.py
    output-dir: .
    output-file: erriez-midi-sysex-io-linux
    include-data-dir: images=images
  data=data
  
    mode: standalone
    enable-plugins: pyside6
    working-directory: .
    onefile: true
    assume-yes-for-downloads: true
  env:
    ...
```

Your workflow file:
```
uses: Nuitka/Nuitka-Action@v1.2
        with:
          nuitka-version: 2.5.5
          script-name: main.py
          output-dir: .
          output-file: erriez-midi-sysex-io-linux
          include-data-dir: |
            images=images
            data=data
          mode: standalone
          enable-plugins: pyside6
```

In my cases i get instead:

```
Run Nuitka/Nuitka-Action@main
  with:
    script-name: start.py
    mode: standalone
    output-filename: ***
    output-dir: dist
    windows-icon-from-ico: logo/logo.ico
    working-directory: .
    nuitka-version: main
    assume-yes-for-downloads: true
```

As you can see there is no extra `onefile: true`
