### ISSUE TITLE
Enhanced yt_dlp configuration to avoid including more than Youtube by default

### ISSUE THREAD

**Issue by kaneryu** [Nuitka/Nuitka#3269]
Hey,
I was using yt_dlp in my project just to fetch the download links to youtube videos, but when compiling, it tries to inculde a file with over 15 thousand lines. This is because yt_dlp does not just do youtube, but hundreds of other video download services. This caused the compilation time to be a few hours (maybe, i never ended up waiting more than 30 mins)

I was able to remove all classes not related to youtube from the file, and it works fine. I read in the yaml config docs that if you make a useful change, you should submit a PR, but since this is removing functionality, I decided to ask first. Also, how should I submit the yaml file, if you guys want it?

**Comment by kaneryu** [comment]
[nuitka-fix.config.yml.txt](https://github.com/user-attachments/files/18192758/nuitka-fix.config.yml.txt)
The config is above ^, but remove the .txt extention

**Comment by kayhayen** [comment]
The module code change probably should be done with replacements, but I guess I can compare with what you changed, or is this actually some sort of new implementation for the module?

**Comment by kayhayen** [comment]
I should have read your description to the end first. So this is about not following all kinds of modules right away. We have configuration that just doesn't follow imports, should that be sufficient? This is from the pygame configuration. In one case it's silently ignoring pygame.tests and doesn't include that unless user asks for unittest module to be allowed, in the other, cv2 is not followed, with a message displayed to the user, informing them that they can still enable that.

```
  anti-bloat:
    - no-auto-follow:
        'pygame.tests': 'ignore'
      when: 'not use_unittest'
    - no-auto-follow:
        'cv2': 'camera functionality via OpenCV-Python (cv2)'
```

Can you work off that? Also, it would be nice to have like a hello world yt download example that could be used to test it.

**Comment by kaneryu** [comment]
> We have configuration that just doesn't follow imports

The file is required, we can't just not import it -- But at the same time, it does contain hundreds upon hundreds of classes that users most likely will not need (it's called youtube-dl not every-single-website-dl, after all). I don't think that solution you listed (pygame example) would work. However, I will try to rewrite it with replacements instead of copy and pasting the code, if that is an issue.

**Comment by kaneryu** [comment]
> Also, it would be nice to have like a hello world yt download example that could be used to test it.

I'll make that in a few minutes. I've actually already tested the yaml with one of my applications successfully already.

**Comment by kayhayen** [comment]
Configuration is bound by when conditions. These could be controlled by module parameters if it makes sense. The advantage of not following the imports even with `--follow-imports` is that you can override that by adding explicit follows for the specific modules. I will look at what you come with, and maybe have some sort of module parameter if it makes sense.

But generally the configuration should be one size fits all.

For Django we use parameters like this, which kind of replaces a whole plugin, by making things dependent on even variables determined at runtime. But the parameter can be used in the `when` clauses of all configuration, and could be used to enable or disable specific settings.

```
- module-name: 'django.core.management' # checksum: cb686c29
  parameters:
    - 'name': 'settings-module'
      'values': 'checkModuleName(value)'
  variables:
    setup_code:
      - 'import os, importlib'
      - 'settings = importlib.import_module(os.getenv("PARAMETER_SETTINGS_MODULE")) if os.getenv("PARAMETER_SETTINGS_MODULE") else None'
    declarations:
      'django_installed_apps': 'settings.INSTALLED_APPS if settings else ()'
    environment:
      'PARAMETER_SETTINGS_MODULE': 'get_parameter("settings-module", "")'
  anti-bloat:
    # This makes exceptions to the "*" dependency in the
    # implicit-imports section below.
    - no-follow:
        'django.core.management.commands.test': 'disable tests'
      when: 'not use_pytest'
  implicit-imports:
    - depends:
        - 'django.core.management.commands.*'
        - 'get_parameter("settings-module", ())'
        - '["%s.management.commands.*" % x for x in get_variable("django_installed_apps")]'
        - 'get_variable("django_installed_apps")'

  options:
    checks:
      - description: "Django settings module must be specified with '--module-parameter=django-settings-module=<settings_module_name>'"
        support_info: 'parameter'
        when: 'get_parameter("settings-module", None) is None'
```

But I am not asking that level of quality, since it involves working with unterdocumented functionality that we use only in 3 instances so far. If you make it clear what changes are needed, that will be great already.
