### ISSUE TITLE
Nuitka takes extremely long time and compiler is out of heap space in pass 2

### ISSUE THREAD

**Issue by TrueRou** [Nuitka/Nuitka#3353]
It seems like sqlalchemy made something wrong.

## Brief Log

```
Nuitka-Options: Used command line options: --include-data-dir=alembic=alembic --include-data-dir=templates=templates --mode=app --lto=no --assume-yes-for-downloads --output-dir=build --script-name=deepseek_wechat_automation/main.py
Nuitka: Starting Python compilation with Nuitka '2.6.6' on Python (flavor CPython Official), '3.12' commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Using module 'trio._core._ki' (version 0.29.0) with incomplete support: Disabled careful handling of KeyboardInterrupt in 'trio'
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to create Qt image objects.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Unexpected output from this command:
<clcache> /Fomodule.sqlalchemy.dialects.oracle.dictionary.obj /c "module.sqlalchemy.dialects.oracle.dictionary.c" /std:c11 /nologo /wd5105 /wd4391 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D_WIN32_WINNT=0x0601 /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\HOSTED~1\windows\Python\312~1.9\x64\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\HOSTED~1\windows\Python\312~1.9\x64\include /I. /IC:\HOSTED~1\windows\Python\312~1.9\x64\Lib\SITE-P~1\nuitka\build\include /IC:\HOSTED~1\windows\Python\312~1.9\x64\Lib\SITE-P~1\nuitka\build\static_src /IC:\HOSTED~1\windows\Python\312~1.9\x64\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
D:\a\deepseek-wechat-automation\deepseek-wechat-automation\build\main.build\module.sqlalchemy.dialects.oracle.dictionary.c(1241) : fatal error C1002: compiler is out of heap space in pass 2

scons: *** [module.sqlalchemy.dialects.oracle.dictionary.obj] Error 3221225725
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

## Full Log

https://gist.github.com/TrueRou/837f2248d28a747b7285cdb07c387e16

## action.yml

```yaml
name: Build Binary

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml" # we consider version has been bumped

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --no-cache --no-interaction

      - name: Build Python script
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: deepseek_wechat_automation/main.py
          include-data-dir: |
            alembic=alembic
            templates=templates
          mode: app
          lto: no

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true

      - name: Release for Windows
        uses: svenstaro/upload-release-action@v2
        with:
          tag: latest
          prerelease: false
          overwrite: true
          file: build/main.exe
          asset_name: deepseek-wechat-automation-windows.exe
          release_name: deepseek-wechat-automation
```

## pyproject.toml

```toml
[tool.poetry]
name = "deepseek-wechat-automation"
version = "1.0.1"
description = ""
authors = ["Usagi no Niku <chenbohan911@163.com>"]
readme = "README.md"
packages = [
    { include = "deepseek_wechat_automation" }
]

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.28.1"
python-dotenv = "^1.0.1"
fastapi = "^0.115.8"
sqlalchemy = "^2.0.38"
sqlmodel = "^0.0.22"
apscheduler = "^3.11.0"
alembic = "^1.14.1"
httpx = "^0.28.1"
openai = "^1.63.0"
uvicorn = "^0.34.0"
jinja2 = "^3.1.5"
python-multipart = "^0.0.20"
pywin32 = "^308"
pillow = "^11.1.0"
emoji = "^2.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
