### ISSUE TITLE
How to correctly include cryptography into a module with a config file?

### ISSUE THREAD

**Issue by BEEugene** [Nuitka/Nuitka#3396]
Hi! 

I'm trying to include cryptography to a module to be able to use it for data decryption inside another python script.
Here is the command and output

```
python -m nuitka --module .\model_enryption\decryption.py --include-package=cryptography --user-package-configuration-file=nuitka-config.yaml
Nuitka-Options: Used command line options: --module .\model_enryption\decryption.py --include-package=cryptography --user-package-configuration-file=nuitka-config.yaml
Nuitka: Starting Python compilation with Nuitka '2.6.8' on Python (flavor CPython Official), '3.10' commercial grade 'not installed'.
Nuitka-Inclusion:WARNING: Not allowed to include module 'cryptography.hazmat.bindings._rust.openssl' due to 'Extension modules cannot be inspected.'.
Nuitka-Inclusion:WARNING: Cannot include extension module 'cryptography.hazmat.bindings._rust' unless using at least standalone mode, where they would be copied. In this mode, extension modules are not part of the compiled     
Nuitka-Inclusion:WARNING: result, and therefore asking to include them makes no sense.
Nuitka-Inclusion:WARNING: Not allowed to include module 'cryptography.hazmat.bindings._rust' due to 'Extension modules cannot be inspected.'.
Nuitka: Completed Python level compilation and optimization.                                       
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                         
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend C linking with 75 files (no progress information available for this stage).
Nuitka-Scons: Compiled 75 C files using clcache with 75 cache hits and 0 cache misses.
Nuitka: Keeping build directory 'decryption.build'.
Nuitka: Successfully created 'D:\Local_drive\Pycharm\dc-api-service\decryption.cp310-win_amd64.pyd'.
```

I've tried to do this without confg file and with it, but when I do `
from cryptography.fernet import Fernet` in my other script I recieve thing like that:

```
Traceback (most recent call last):
  File "...\decryption.py", line 4, in <module decryption> #that is a module which I built
  File "...\cryptography\fernet.py", line 14, in <module cryptography.fernet>
  File "...\cryptography\exceptions.py", line 9, in <module cryptography.exceptions>
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._rust
```

I've tried to make a config file, but had no luck.

```
#nuitka-config.yaml
- module-name: 'cryptography.hazmat.bindings'
  implicit-imports:
    - depends:
        - 'cryptography.hazmat.bindings._rust'
  data-files:
    dest_path: ".venv/Lib/cryptography/hazmat/bindings"
    patterns:
    - "*.pyi"
    - "*.pyd"
  dlls:
    - from_filenames:
        relative_path: './hazmat/bindings'
        prefixes:
          - '*'

        suffixes:
          - 'pyd'

      dest_path: 'output_dir'

```
How do I fix the config to put the cryptography in a module?

python -m nuitka --version
2.6.8        
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Local_drive\Pycharm\dc-api-service\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\bin\Hostx64\x64\cl.exe (cl 14.3).
