### ISSUE TITLE
windows-console-mode attach not behaving as expected

### ISSUE THREAD

**Issue by MatthiasJaeger** [Nuitka/Nuitka#3528]
# Bug Report

## 🐛 Bug Description

Script compiled with `windows-console-mode` set to `attach` does not output to terminal it is started from. 

## 🖥️ Environment

Nuitka running in Github action on windows latest. No packages pinned.

Python: 3.13.5
Nuitka: 2.7.10

### 1. "Hello World" Test (if applicable)

n/a

### 2. Short, Self-Contained, Correct, Eligible (SSCCE) Example

```python
# nuitka-project: --windows-console-mode=attach

print('foo')
```

### 3. Nuitka Command Line Options

see above

## 📉 Expected Behavior

When started from Windows 10 terminal (as started by typing `cmd` in the start menu) it should output "foo".

## 📄 Actual Behavior & Output

When started from Windows 10 command line no output occurs. This is the case both for `standalone` and `onefile` modes.

For comparison if the console mode is not set the output occurs in the same terminal it is started from.

**Comment by kayhayen** [comment]
I cannot reproduce it in my git bash in Visual Code, and I just tested CMD.EXE, and it works fine with both 3.13 and 3.10, and there shouldn't be much of a version specity with this. Since 3.13 you cannot use MinGW64 but you didn't care enough anyway to make a proper report with all requested information, e.g. not --version, so this is probably you not checking properly.

**Comment by MatthiasJaeger** [comment]
Sorry if this is not sufficient. Especially so if it wasted your time. Let me try to add what additional information I can provide.

This is the --version output
```
2.7.10
Commercial: None
Python: 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]
Flavor: CPython Official
GIL: yes
Executable: C:\hostedtoolcache\windows\Python\3.13.5\x64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe (cl 14.3).
```
And this is the full github action:
``` yml
name: windows_build_standalone.yml

on:
  push:
    tags:
      - '**'
  pull_request:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable Win
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: Test.py
          output-file: Test.exe
          product-version: 1.0.0.0
          file-version: 1.0.0.0
          copyright: "© ..."
          report: compilation-report.xml
          mode: onefile
          msvc: latest

      - name: Get Nuitka Version Information
        run: |
          python -m nuitka --version

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Compilation Report Standalone
          if-no-files-found: warn
          path: compilation-report.xml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifact Standalone
          if-no-files-found: error
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            build/*.dist/**/*
          include-hidden-files: true

```

Just tested it using CMD.EXE as well resulting in the same behavior.
