### ISSUE TITLE
Use Github actions for Windows and macOS CI

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#551]
Has there been an attempt to add Windows CI?

Travis CI for Windows is quite good, and there is a reasonable support base able to help at https://travis-ci.community/c/environments/windows

I was able to make it almost like AppVeyor for the coala-bears CI; see e.g. Windows icon on https://travis-ci.org/coala/coala-bears/builds/581997859 for a 30min job setting up lots of chocolatey packages.

Azure also has Linux, macOS and Windows , so switching to that is also an option.

**Comment by jayvdb** [comment]
ping @kayhayen , do you have any preference for how I proceed with this?

**Comment by kayhayen** [comment]
Sorry for the late reply, @jayvdb things are busy for me privately. However, I have lots of response to this, and didn't take the time yet.

I had started to use AppVeyor for Nuitka, but noticed early on, they were not giving too many cycles to build jobs. However, their offering is of course attractive. What I preferred Travis for is deep integration with Github that was fully automatic. I never got that to work with AppVeyor, which is why I recently disabled that one job I had, where it produces the MSI files. I am not even sure, how useful those even are, and I never managed to automate the download of the MSI artifacts from the webhooks.

Basically all lack of time. We have a Linux only public CI of our own, nightshift.nuitka.net, that has fallen into disrepair, since Buildbot failed to work with Apache and only Nginx, but that works less well with the SSL certificate renewal. I will turn to that this weekend I hope. There we can burn as many cycles as we want. But it's ugly since it's not automatically adding branches, i.e. PRs do not get built. But for many, that is also far from needed to run the whole suite of compilations.

If you want to take this on, very well. I also mean to invite you to the Nuitka organisation, if you are interested, which I hope. Esp. if you are interested in that 3.8 work with test suites, and other stuff, you are more than welcome.

Again sorry for the late reply.

Yours,
Kay

**Comment by jayvdb** [comment]
Ok, I'll make a start on Travis CI, and let you know how I go.
I have had fairly deep integration with AppVeyor, including artifacts.
AppVeyor provides more variation of Windows environments - different images, but I havent used the non-default ones much.

We can have both operational in order to spread the load, if needed.

Yes I am interested in joining the org.

**Comment by kayhayen** [comment]
Feel free to have your own branch in the central repository. That way I will see it easier. I added you to the pushers as part of the invite.

I indeed had very good experience with AppVeyor, but I didn't use the `.yml` file in their instance, that's actually pretty annoying to try out things that way, isn't it. But it also is the only way to share stuff. 

They have VMs with all Python's installed, etc. and it seems even WSL was added recently. I think AppVeyour still has access to Nuitka, if you want to go there as well. I think starting with Travis is a good idea. I can lookup what is still on AppVeyor, I might have deleted it 2 months ago though, when it failed to build MSIs and I noticed it still existed and only wasted energy.

**Comment by brendanator** [comment]
I recommend using Github actions for this (which should be available for everyone sometime in November, or you can sign up to get early access)

1. Deep integration with GitHub, obviously
2. Has Windows, Mac and Linux VMs

We've created a build for our project that runs on all OSes and it's been fantastic. Here's a slimmed down example that would belong in `.github/workflows/test_nuitka.yml`

```yml
name: Nuitka tests

on:
  pull_request: {}
  push:
    branches: master
    tags: '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4

    - name: Install dependencies
      run: |
        pip install nuitka

    - name: Build with nuitka
      run: python -m nuitka

    - name: Run tests
      run: ...

  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Python 3.7.4 using Conda
      run: |
        sudo chown -R $USER $CONDA
        $CONDA/bin/conda install python=3.7.4

    - name: Install dependencies
      run: |
        pip install nuitka

    - name: Build with nuitka
      run: python -m nuitka

    - name: Run tests
      run: ...

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4

    - name: Install MinGW using Conda
      shell: bash
      run: $CONDA/Scripts/conda install m2w64-gcc libpython

    - name: Install dependencies with pipenv
      shell: bash
      run: |
        pip install nuitka

    - name: Build with nuitka
      shell: bash
      run: CC=$CONDA/Library/mingw-w64/bin/gcc.exe pipenv run build

    - name: Run tests
      shell: bash
      run: ...
```
