### ISSUE TITLE
Segmentation fault with importing PyQt5 5.14.0

### ISSUE THREAD

**Issue by samschott** [Nuitka/Nuitka#601]
The standalone executable works when built with PyQt5 5.13.1 but crashes with a segmentation fault on startup with 5.14.0.

Build command:

```
python3 -m nuitka --follow-imports --standalone --enable-plugin=qt-plugins=sensible,styles --lto main_pyqt.py
```

System info:

Nuitka: 0.6.6
Python: 3.7.6 (default, Jan  6 2020, 18:03:35) 
Executable: /usr/local/opt/python/bin/python3.7
OS: Darwin
Arch: x86_64

The file 'main_pyqt.py' is a short minimum working example with:

```python
import sys
from PyQt5 import QtWidgets

app = QtWidgets.QApplication(['HelloWorld'])

button = QtWidgets.QPushButton('Click me!')
button.show()

sys.exit(app.exec())
```

I am happy to provide more information but don't really know where to start to debug this. The console output is only `zsh: segmentation fault main_pyqt`.

**Comment by JorjMcKie** [comment]
Just confirming that everything works fine on Windows 10, 64bit Python 3.7 and 3.8, PyQt5 1.14.1.
I compiled it using both, vanilla nuitka and hinted compilation.
It ought to be OSX specific then.

**Comment by saschaludwig** [comment]
Try to create the directory PyQt5/Qt inside the build dir. Like stated here:
https://github.com/Nuitka/Nuitka/issues/680#issuecomment-616292573

**Comment by photoszzt** [comment]
@JorjMcKie @saschaludwig I'm hitting the same problem and making an empty Qt dir doesn't solve the problem. I'm creating an app bundle and I'm using PyQt5 5.15.6.

**Comment by DarthNihilus1** [comment]
same problem here as well using a pyqt5 app
5.15.7_1 
on macos apple silicon

**Comment by kayhayen** [comment]
PyQt5 is not well supported at all, it has lots of issues, and you are using ancient versions of Nuitka. It may be necessary to build a bundle on macOS, it cannot be used without that, so use `--macos-create-app-bundle` there.

**Comment by alitrack** [comment]
here is the solution for PyQt5 onefile 
an example compile [calcuator](https://github.com/pythonguis/15-minute-apps/tree/master/calculator)

```bash
cd 15-minute-apps/calculator
mkdir -p PyQt5/Qt5
touch PyQt5/Qt5/.keep
python -m nuitka \
          --debug \
          --standalone \
          --onefile\
          --enable-plugin=pyqt5\
          --macos-create-app-bundle\
          --output-dir=build\
          --assume-yes-for-download\
          --macos-app-version=2.0\
          --disable-console\
          --include-data-dir=PyQt5/Qt5=PyQt5/Qt5  \
          calculator.py
```

**Comment by kayhayen** [comment]
@alitrack can you confirm this applies to recent Nuitka? If so, this should also help:

```
- module-name: 'PyQt5'
  data-files:
    empty_dirs:
      - 'Qt5'
```

If used with `--user-package-configuration-file` that should work too.

**Comment by alitrack** [comment]
## env
- nuitka:1.5.7
- PyQt5: 5.15.2

## works with modification of `standard.nuitka-package.config.yml`
<img width="453" alt="image" src="https://user-images.githubusercontent.com/20972179/237063584-d4856308-1f01-4d92-98d3-78b9135e6a3f.png">


##  had better include Qt folder too, 

```yml
- module-name: 'PyQt5'
  options:
    checks:
      - description: 'PyQt5 is a GUI framework'
        console: 'recommend'
        when: 'plugin("pyqt5")'
      - description: 'PyQt5 cannot be used without bundle'
        macos_bundle: 'yes'
        when: 'macos and not anaconda and plugin("pyqt5")'
      - description: 'PyQt5 cannot be signed unless onefile'
        macos_bundle_as_onefile: 'yes'
        when: 'macos and plugin("pyqt5")'
  data-files:
    empty_dirs:
      - 'Qt5'
      - 'Qt'
```    
https://github.com/Nuitka/Nuitka/issues/680#issuecomment-616292573

## --user-package-configuration-file does not work
<img width="1044" alt="image" src="https://github.com/Nuitka/Nuitka/assets/20972179/09b38cae-7b3f-438d-b1a2-d45f2ed35b6c">

<img width="245" alt="image" src="https://github.com/Nuitka/Nuitka/assets/20972179/13d564fe-7f4f-4e2d-8e1e-2633e8a1cfe1">
