### ISSUE TITLE
Windows Nuitka builds failing when using pipenv in Github actions

### ISSUE THREAD

**Issue by Hellebore** [Nuitka/Nuitka#623]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
  0.6.7
  Python: 3.7 (Github python-version 3.7)
  OS: Windows Server 2019 (Github windows-latest)
```
* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

pip

* If possible please supply a Short, Self Contained, Correct, Example
that demonstrates the issue i.e a small piece of code which reproduces
the issue and can be run with out any other (or as few as possible)
external dependencies.
```
cat hello.py
print("Hello World")
pipenv run python -m nuitka hello.py --standalone --assume-yes-for-downloads
```
This produces the following:
```
Error, mismatch between Python ('x86_64') and C compiler ('pei-x86-64') arches.
```
This was working until a couple of days ago, possibly when an update to Github's windows-latest image happened.

The Github config I am using is based on the nuitka one:
```
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install MinGW using Conda
      shell: bash
      run: $CONDA/Scripts/conda install m2w64-gcc libpython

    - name: Install dependencies with pipenv
      shell: bash
      run: |
        pip install pipenv
        pipenv install --deploy --dev

    - name: Build with nuitka
      shell: bash
      run: CC=$CONDA/Library/mingw-w64/bin/gcc.exe make build_windows
```
